### ISSUE TITLE
Can't send multiple message when using promise/await

### ISSUE THREAD

**Issue by tidusvn05** [Wolke/botbuilder-linebot-connector#12]
Hi all,

I just got a problem.

[Env]
push: true

[sample Code]
session.send("msg 1"); // => be run
await function();// => be run

session.send("msg 2"); // => not run
console.log("debug 1"); // => be run
session.endDialog("") // => not run

As below code, session can't run if wait some seconds from wait/promise function.

Anyone can help me ?
Thank in advance!

**Comment by Wolke** [comment]
can you give me some code ?

**Comment by tidusvn05** [comment]
my code in dialog file.
```

import axios from 'axios';

module.exports = [
  async function(session, args, next) {
    session.send('message 1');
    session.send('message 2');
    // Send the message.
    let response = await axios({
      method:'get',
      url:'http://bit.ly/2mTM3nY',
      responseType:'stream'
    });
    session.endDialog("final message");
    return;
  }
]
```

if use request-promise instead of axios, same problem got.

**Comment by Wolke** [comment]
LINE message reply api can not be wait for 2 seconds.
If you have to wait for your function.
I suggest you to set push api
